### PR TITLE
feat(simple): increase reusability of the operator

### PR DESCRIPTION
**Pull request by tribock**
- remove deployment name from operator
- add operator property to values file
- enable operator to manage multiple components in the same namespace

### CODE REVIEW

**Comment by dmlabs** [comment]
@tribock As discussed on our separate channel, it would make more sense to separate your suggested simple-operator from the rkm project, as the one can use the simple-operator also for other use cases.
Do you want to to host the project for the simple-operator or shall I?
I would also suggest the the name "patch-operator" for the new project.
What do you think?

**Comment by tribock** [comment]
@dmlabs I completely agree with you. As you already hosted the rkm-project I would suggest that you host the patch operator as well.

**Comment by dmlabs** [comment]
@tribock I created the project https://github.com/dmlabs/patch-operator.
The project already contain your suggestions and I also invited you as a contributor.
If you are OK with it, I will close this pull request without a merge.

**Comment by tribock** [comment]
maybe should thing about including the patch-operator as helm chart into the existing charts. maybe this will increase the complexity of the architecture at first but i expect a bigger gain on reusaility for this operator. what do you think about it?

**Comment by dmlabs** [comment]
I agree with that.
Nevertheless I prefer to first concentrate on completing the RKM features and functionality.
I will file an issue for the integration of the patch-operator, link it here and then close the pull request.

**Comment by dmlabs** [comment]
Opened this issue to address the topic of this pull request:
https://github.com/dmlabs/rkm/issues/6

**Pull request closed without merging**
